sudo: required
services:
  - docker

script:
  - docker build -t chackop/node .
  - docker images chackop/node

before_deploy:
  - docker login -u <username> -p <password>

deploy:
  provider: script
  script: docker push chackop/node
  on:
    branch: master
